package com.auth.center.service.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.auth.center.entity.ConnectedApp;
import com.auth.center.entity.ConnectedAppSecret;
import com.auth.center.mapper.ConnectedAppMapper;
import com.auth.center.mapper.ConnectedAppSecretMapper;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.builder.MapperBuilderAssistant;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;

/**
 * {@link ConnectedAppServiceImpl} 纯 Mockito 单测。
 *
 * 覆盖: CRUD 全流程、密钥生成/撤销/上限守卫、authenticate 正常/异常路径。跨系统统一模型下,应用只保留
 * targetSystem(嵌入进哪个系统),内容作用域由目标系统按真实用户裁决,故无资产范围断言。
 */
class ConnectedAppServiceImplTest {

    // ── mock 依赖 ──────────────────────────────────────────────────

    private ConnectedAppMapper appMapper;
    private ConnectedAppSecretMapper secretMapper;
    private ConnectedAppServiceImpl svc;

    // ── 初始化 ─────────────────────────────────────────────────────

    /** LambdaQueryWrapper 依赖 TableInfo 元数据,纯单测无 Spring 需手动初始化。 */
    @BeforeAll
    static void initTableInfo() {
        TableInfoHelper.initTableInfo(
                new MapperBuilderAssistant(new MybatisConfiguration(), ""), ConnectedApp.class);
        TableInfoHelper.initTableInfo(
                new MapperBuilderAssistant(new MybatisConfiguration(), ""),
                ConnectedAppSecret.class);
    }

    @BeforeEach
    void setUp() {
        appMapper = Mockito.mock(ConnectedAppMapper.class);
        secretMapper = Mockito.mock(ConnectedAppSecretMapper.class);
        svc = new ConnectedAppServiceImpl(appMapper, secretMapper);
    }

    // ── listAll ────────────────────────────────────────────────────

    @Test
    void shouldReturnEmptyListWhenNoApps() {
        when(appMapper.selectList(any(LambdaQueryWrapper.class)))
                .thenReturn(Collections.emptyList());

        List<Map<String, Object>> result = svc.listAll();

        assertTrue(result.isEmpty(), "无应用时应返回空列表");
    }

    @Test
    void shouldReturnAppWithSecretsWhenAppsExist() {
        ConnectedApp app = buildApp(1L, "TestApp", "client-1", "enabled");
        when(appMapper.selectList(any(LambdaQueryWrapper.class))).thenReturn(List.of(app));

        ConnectedAppSecret secret = new ConnectedAppSecret();
        secret.setSecretId("sec_abc");
        when(secretMapper.selectList(any(LambdaQueryWrapper.class))).thenReturn(List.of(secret));

        List<Map<String, Object>> result = svc.listAll();

        assertEquals(1, result.size(), "应返回 1 个应用");
        Map<String, Object> item = result.get(0);
        assertEquals("TestApp", item.get("name"));
        assertEquals("client-1", item.get("clientId"));
        assertEquals("bi", item.get("targetSystem"), "应回传目标系统");
        assertEquals(1, item.get("secretCount"));
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> secrets = (List<Map<String, Object>>) item.get("secrets");
        assertEquals("sec_abc", secrets.get(0).get("secretId"));
    }

    // ── create ─────────────────────────────────────────────────────

    @Test
    void shouldCreateAppWithAutoGeneratedClientIdAndSecret() {
        // insert 不抛异常即表示成功
        Map<String, Object> result = svc.create("MyApp", "[\"example.com\"]", null, null, 100L);

        // 验证 app 被 insert
        ArgumentCaptor<ConnectedApp> appCaptor = ArgumentCaptor.forClass(ConnectedApp.class);
        verify(appMapper).insert(appCaptor.capture());
        ConnectedApp saved = appCaptor.getValue();
        assertEquals("MyApp", saved.getName());
        assertNotNull(saved.getClientId(), "clientId 应自动生成");
        assertEquals("bi", saved.getTargetSystem(), "targetSystem 缺省为 bi");
        assertEquals("enabled", saved.getStatus());
        assertEquals(100L, saved.getCreatedBy());

        // 验证 secret 被 insert
        verify(secretMapper).insert(any(ConnectedAppSecret.class));

        // 返回值包含 secretId 和 secretValue
        assertNotNull(result.get("secretId"));
        assertNotNull(result.get("secretValue"));
        assertNotNull(result.get("clientId"));
    }

    @Test
    void shouldUseProvidedTargetSystemWhenNotNull() {
        svc.create("App2", null, "agent", null, 1L);

        ArgumentCaptor<ConnectedApp> captor = ArgumentCaptor.forClass(ConnectedApp.class);
        verify(appMapper).insert(captor.capture());
        assertEquals("agent", captor.getValue().getTargetSystem());
    }

    // ── update ─────────────────────────────────────────────────────

    @Test
    void shouldThrowWhenUpdateNonExistentApp() {
        when(appMapper.selectById(999L)).thenReturn(null);

        IllegalArgumentException ex =
                assertThrows(
                        IllegalArgumentException.class,
                        () -> svc.update(999L, "x", null, null, null, null));
        assertTrue(ex.getMessage().contains("999"));
    }

    @Test
    void shouldUpdateOnlyProvidedFields() {
        ConnectedApp existing = buildApp(1L, "Old", "cid", "enabled");
        when(appMapper.selectById(1L)).thenReturn(existing);

        ConnectedApp updated = svc.update(1L, "New", null, null, "disabled", null);

        assertEquals("New", updated.getName(), "name 应被更新");
        assertEquals("disabled", updated.getStatus(), "status 应被更新");
        assertEquals("bi", updated.getTargetSystem(), "未传 targetSystem 时保持不变");
        verify(appMapper).updateById(existing);
    }

    @Test
    void shouldUpdateTargetSystemWhenProvided() {
        ConnectedApp existing = buildApp(1L, "App", "cid", "enabled");
        when(appMapper.selectById(1L)).thenReturn(existing);

        ConnectedApp updated = svc.update(1L, null, null, "tracking", null, null);

        assertEquals("tracking", updated.getTargetSystem(), "targetSystem 应被更新");
    }

    // ── delete ─────────────────────────────────────────────────────

    @Test
    void shouldThrowWhenDeleteNonExistentApp() {
        when(appMapper.selectById(999L)).thenReturn(null);

        assertThrows(IllegalArgumentException.class, () -> svc.delete(999L));
    }

    @Test
    void shouldCascadeDeleteSecretsWhenDeleteApp() {
        ConnectedApp app = buildApp(1L, "App", "cid", "enabled");
        when(appMapper.selectById(1L)).thenReturn(app);

        svc.delete(1L);

        // 先删密钥再删应用
        verify(secretMapper).delete(any(LambdaQueryWrapper.class));
        verify(appMapper).deleteById(1L);
    }

    // ── generateSecret ─────────────────────────────────────────────

    @Test
    void shouldThrowWhenGenerateSecretForNonExistentApp() {
        when(appMapper.selectById(999L)).thenReturn(null);

        assertThrows(IllegalArgumentException.class, () -> svc.generateSecret(999L));
    }

    @Test
    void shouldThrowWhenSecretCountAtMax() {
        ConnectedApp app = buildApp(1L, "App", "cid", "enabled");
        when(appMapper.selectById(1L)).thenReturn(app);
        // 已有 2 个密钥（上限）
        when(secretMapper.selectCount(any(LambdaQueryWrapper.class))).thenReturn(2L);

        IllegalStateException ex =
                assertThrows(IllegalStateException.class, () -> svc.generateSecret(1L));
        assertTrue(ex.getMessage().contains("Maximum"));
    }

    @Test
    void shouldGenerateSecretWhenUnderLimit() {
        ConnectedApp app = buildApp(1L, "App", "cid", "enabled");
        when(appMapper.selectById(1L)).thenReturn(app);
        // 首次 selectCount=1(低于上限), 插入后 selectCount=2(等于上限,但不超)
        when(secretMapper.selectCount(any(LambdaQueryWrapper.class))).thenReturn(1L, 2L);

        Map<String, String> result = svc.generateSecret(1L);

        assertNotNull(result.get("secretId"));
        assertNotNull(result.get("secretValue"));
        verify(secretMapper).insert(any(ConnectedAppSecret.class));
    }

    @Test
    void shouldRollbackSecretWhenConcurrentInsertExceedsMax() {
        ConnectedApp app = buildApp(1L, "App", "cid", "enabled");
        when(appMapper.selectById(1L)).thenReturn(app);
        // pre-insert=1, post-insert=3(并发超限)
        when(secretMapper.selectCount(any(LambdaQueryWrapper.class))).thenReturn(1L, 3L);

        assertThrows(IllegalStateException.class, () -> svc.generateSecret(1L));
        // 插入后又删除 — 共 1 次 insert + 1 次 delete
        verify(secretMapper).insert(any(ConnectedAppSecret.class));
        verify(secretMapper).delete(any(LambdaQueryWrapper.class));
    }

    // ── revokeSecret ───────────────────────────────────────────────

    @Test
    void shouldThrowWhenRevokeNonExistentSecret() {
        when(secretMapper.delete(any(LambdaQueryWrapper.class))).thenReturn(0);

        assertThrows(IllegalArgumentException.class, () -> svc.revokeSecret(1L, "sec_notfound"));
    }

    @Test
    void shouldRevokeExistingSecret() {
        when(secretMapper.delete(any(LambdaQueryWrapper.class))).thenReturn(1);

        svc.revokeSecret(1L, "sec_abc");

        verify(secretMapper).delete(any(LambdaQueryWrapper.class));
    }

    // ── authenticate ───────────────────────────────────────────────

    @Test
    void shouldReturnNullWhenClientIdIsNull() {
        assertNull(svc.authenticate(null, "secret"));
    }

    @Test
    void shouldReturnNullWhenClientSecretIsNull() {
        assertNull(svc.authenticate("cid", null));
    }

    @Test
    void shouldReturnNullWhenAppNotFound() {
        when(appMapper.selectOne(any(LambdaQueryWrapper.class))).thenReturn(null);

        assertNull(svc.authenticate("unknown-cid", "secret"));
    }

    @Test
    void shouldReturnNullWhenAppIsDisabled() {
        ConnectedApp app = buildApp(1L, "App", "cid", "disabled");
        when(appMapper.selectOne(any(LambdaQueryWrapper.class))).thenReturn(app);

        assertNull(svc.authenticate("cid", "secret"));
        // 不应查密钥
        verify(secretMapper, never()).selectOne(any(LambdaQueryWrapper.class));
    }

    @Test
    void shouldReturnNullWhenSecretHashMismatch() {
        ConnectedApp app = buildApp(1L, "App", "cid", "enabled");
        when(appMapper.selectOne(any(LambdaQueryWrapper.class))).thenReturn(app);
        when(secretMapper.selectOne(any(LambdaQueryWrapper.class))).thenReturn(null);

        assertNull(svc.authenticate("cid", "wrong-secret"));
    }

    @Test
    void shouldReturnAppWhenAuthenticationSucceeds() {
        ConnectedApp app = buildApp(1L, "App", "cid", "enabled");
        when(appMapper.selectOne(any(LambdaQueryWrapper.class))).thenReturn(app);

        ConnectedAppSecret matchingSecret = new ConnectedAppSecret();
        matchingSecret.setAppId(1L);
        when(secretMapper.selectOne(any(LambdaQueryWrapper.class))).thenReturn(matchingSecret);

        ConnectedApp result = svc.authenticate("cid", "any-secret");

        assertNotNull(result);
        assertEquals(1L, result.getId());
    }

    // ── 工具方法 ───────────────────────────────────────────────────

    private static ConnectedApp buildApp(Long id, String name, String clientId, String status) {
        ConnectedApp app = new ConnectedApp();
        app.setId(id);
        app.setName(name);
        app.setClientId(clientId);
        app.setStatus(status);
        app.setTargetSystem("bi");
        return app;
    }
}
